export enum ConfigKeys {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  JWT_SECRET = 'JWT_SECRET',
  ENABLE_SYSLOG = 'ENABLE_SYSLOG',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_USER = 'MYSQL_USER',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  MYSQL_DATABASE = 'MYSQL_DATABASE',
  API_GLOBAL_PREFIX = 'API_GLOBAL_PREFIX',
}
