//# REGIDURIAS;
export const NOMBRE_REGIDURIA_MIN_LENGTH = 5;

//# CIUDADANOS;
export const CIUDADANO_MIN_PASSWORD_LENGTH = 8;
export const CIUDADANO_PASSWORD_SALT_ROUNDS = 10;

export const THROTTLE_TTL_GLOBAL = 60;
export const THROTTLE_LIMIT_GLOBAL = 20;
